name: Build project

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_POSITION_INDEPENDENT_CODE=On
      - name: Build
        run: cmake --build build --parallel
      - name: Build Python package
        working-directory: interfaces/python
        env:
          CFLAGS: -I${{ github.workspace }}/include
          CXXFLAGS: -I${{ github.workspace }}/include
          LDFLAGS: -L${{ github.workspace}}/build/libs
        run: |
          python -m pip install --upgrade pip build
          python -m build
